[package]
name = "calculator-gui-rs"
version = "1.0.0"
authors = ["Jérémy Audiger"]
edition = "2024"
rust-version = "1.99"

[dependencies]
bevy = {
    version = "0.20.0",
    default-features = false,
    features = [
        "bevy_picking",
        "bevy_ui_widgets",
        "bevy_winit",
        "default_font",
        "scene",
        "ui_bevy_render",
        "ui_picking",
        "wayland",
        "webgl2",
        "x11",
    ],
}

[lints.clippy]
all = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }

[profile.dev]
split-debuginfo = "unpacked"

[profile.release]
codegen-units = 1
lto = true
incremental = false
opt-level = "z"
panic = "abort"
strip = "symbols"
