name: Continuous Integration - Audit

on:
  push:
    paths:
      - ".github/workflows/audit.yml"
      - "**/Cargo.toml"
      - "**/Cargo.lock"
  pull_request:
    paths:
      - ".github/workflows/audit.yml"
      - "**/Cargo.toml"
      - "**/Cargo.lock"
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

concurrency:
  group: audit-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read
  checks: write

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache cargo audit registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
            ~/.cargo/bin
            ~/.cargo/advisory-db
          key: audit-${{ hashFiles('**/Cargo.lock') }}

      - name: Run cargo-audit
        uses: actions-rust-lang/audit@v1
        continue-on-error: true
