name: Continuous Deployment

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
    branches: [main]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: jaudiger/reusable-workflows/.github/workflows/deploy-rust-cloudflare-pages.yml@04ca9c1ba0702419876c79c5c5bcc8b44bfb223e
    secrets: inherit
