name: Continuous Deployment

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
    branches: [main]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: jaudiger/reusable-workflows/.github/workflows/deploy-rust-cloudflare-pages.yml@4aef3115afe05a19785b3e14970ecd4f400cc457
    secrets: inherit
